# Generated by Django 5.0.6 on 2025-05-04 12:47

import triptracks.identity.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to=triptracks.identity.models.user.user_profile_photo_path),
        ),
    ]
