# Generated by Django 5.0.6 on 2024-09-28 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car')], max_length=12)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], max_length=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='vehicle_ser_name_371d91_idx'), models.Index(fields=['make'], name='vehicle_ser_make_ef84c3_idx'), models.Index(fields=['model'], name='vehicle_ser_model_809699_idx'), models.Index(fields=['type'], name='vehicle_ser_type_e0bf0f_idx'), models.Index(fields=['fuel_type'], name='vehicle_ser_fuel_ty_cd5cb9_idx'), models.Index(fields=['owner'], name='vehicle_ser_owner_i_7c05b3_idx'), models.Index(fields=['created_at'], name='vehicle_ser_created_684aaf_idx'), models.Index(fields=['updated_at'], name='vehicle_ser_updated_89490a_idx')],
            },
        ),
    ]
