# Generated by Django 5.0.6 on 2024-09-28 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewrelationship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_relations1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewrelationship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_relations2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_crew_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_crew_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='crewrelationship',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='crewrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
