# Generated by Django 5.0.6 on 2024-09-24 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('origin_location', models.CharField(max_length=100)),
                ('origin_lat', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('origin_long', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)])),
                ('destination_location', models.CharField(max_length=100)),
                ('destination_lat', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('destination_long', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)])),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('distance_unit', models.CharField(choices=[('km', 'Km'), ('mile', 'Mile')], max_length=12)),
                ('average_distance_per_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('accomodation_days', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('accomodation_cost_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('calculated_accomodation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('final_accomodation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('final_accomodation_adjustments', models.CharField(blank=True, max_length=250, null=True)),
                ('food_cost_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('calculated_food_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('final_food_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('final_food_adjustments', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_organized', to=settings.AUTH_USER_MODEL)),
                ('travellers', models.ManyToManyField(related_name='trips_participated', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('unit_type', models.CharField(choices=[('item', 'Item'), ('litre', 'L'), ('kg', 'Kg'), ('day', 'Day'), ('night', 'Night')], max_length=12)),
                ('no_of_units', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods_paid', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods_updated', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='trip_service.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('unit_type', models.CharField(choices=[('item', 'Item'), ('litre', 'L'), ('kg', 'Kg'), ('day', 'Day'), ('night', 'Night')], max_length=12)),
                ('no_of_units', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_updated', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trip_service.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('unit_type', models.CharField(choices=[('item', 'Item'), ('litre', 'L'), ('kg', 'Kg'), ('day', 'Day'), ('night', 'Night')], max_length=12)),
                ('no_of_units', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations_paid', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations_updated', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations', to='trip_service.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fuel_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('calculated_fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('final_fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('final_fuel_adjustments', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL)),
                ('passengers', models.ManyToManyField(related_name='trips_as_passenger', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tripvehicles', to='vehicle_service.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicles',
            field=models.ManyToManyField(related_name='trips', to='trip_service.tripvehicle'),
        ),
    ]
