# Generated by Django 5.0.6 on 2025-12-07 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='trip_service.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['author'], name='trip_servic_author__7e202e_idx'), models.Index(fields=['message'], name='trip_servic_message_b67bc8_idx'), models.Index(fields=['trip'], name='trip_servic_trip_id_dd4bc7_idx'), models.Index(fields=['created_at'], name='trip_servic_created_eee321_idx'), models.Index(fields=['updated_at'], name='trip_servic_updated_90e608_idx')],
            },
        ),
    ]
