# Generated by Django 5.0.6 on 2024-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='fuel_cost',
            new_name='calculated_fuel_cost',
        ),
        migrations.AddField(
            model_name='trip',
            name='final_fuel_adjustments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='final_accomodation_adjustments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='final_food_adjustments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
